/** Names of injectionable services, leads to fewer typing errors for most important injections */
export const injectionNames = {
  componentSpecificLoggerFactory: "core:root:component-specific-logger-factory",
  eventBus: "core:root:event-bus",
  handlerProxyFactory: "core:unifier:handler-proxy-factory",
  hookPipeFactory: "core:hook-pipe-factory",
  i18nWrapper: "core:i18n:wrapper",
  i18nInstance: "core:i18n:instance",
  i18nInterpolationResolver: "core:i18n:interpolation-resolver",
  i18nSpecWrapper: "core:i18n:spec-wrapper",
  i18nComponent: "meta:component//core:i18n",
  logger: "core:root:logger",
  localesLoader: "core:unifier:locales-loader",
  metaState: "core:state-machine:meta-states",
  rootComponent: "meta:component//core:root",
  stateFactory: "core:state-machine:state-factory",
  stateNames: "core:state-machine:state-names",
  servicesComponent: "meta:component//core:services",
  usedIntents: "core:state-machine:used-intents",
  unifierComponent: "meta:component//core:unifier",
  userEntityMappings: "core:unifier:user-entity-mappings",
  current: {
    contextStatesProvider: "core:state-machine:current-context-states-provider",
    extraction: "core:unifier:current-extraction",
    entityDictionary: "core:unifier:current-entity-dictionary",
    i18nContext: "core:i18n:current-context",
    i18nTranslateValuesFor: "core:i18n:current-translate-values-for",
    killSessionService: "core:services:current-kill-session-promise",
    logger: "core:root:current-logger",
    responseHandler: "core:unifier:current-response-handler",
    responseHandlerExtensions: "core:unifier:response-handler-extensions",
    requestContext: "core:root:current-request-context",
    stateMachine: "core:state-machine:current-state-machine",
    stateNameProvider: "core:state-machine:current-state-name-provider",
    stateProvider: "core:state-machine:current-state-provider",
    stateSetupSet: "core:state-machine:current-state-setup-set",
    sessionFactory: "core:services:current-session-factory",
    translateHelper: "core:i18n:current-translate-helper",
  },
};
